name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
   
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.3.0
    
    - name: Docker Login
      uses: docker/login-action@v3.2.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: docker.io
        logout: true

    - name: Build and push Docker images
      run: |
        docker build -t tnehara831/fashionfitsme-admin-panel:latest .
        docker push tnehara831/fashionfitsme-admin-panel:latest
